name: nova_grid
description: "A customizable Flutter data table"

homepage: https://github.com/hajul-dhanish/nova_grid
repository: https://github.com/hajul-dhanish/nova_grid
issue_tracker: https://github.com/hajul-dhanish/nova_grid/issues

version: 0.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
